title: Praeci
pronounciation: "pray &middot; see"
maxim: covering NC State and Raleigh
logo:
    path: "/assets/img/Web Logo.png"
prod_url: http://praeci.com

timezone: America/New_York
lang: en-us

author:
    name: Carter Pape
    email: editor@praeci.com

permalink: /:categories/:title

plugins:
    - jekyll-feed

feed:
    path: podcast.xml

strict_front_matter: TRUE

twitter_link: https://twitter.com/PraeciNews
twitter_handle: "PraeciNews"
facebook_link: https://www.facebook.com/Praeci/
donation_link: https://www.paypal.me/CarterPape

cover-photo:
    path: "/assets/img/Web cover.png"

podcast:
    title: "The Praeci Podcast"
    description: "In-depth NC State and Raleigh news, interviews, and more. Delivered every other Monday."
    keywords:
        - nc state
        - ncsu
        - raleigh
        - technician
        - student news
        - student newspaper
    album_art: /assets/img/podcast-album-art.png
    
protected-class:
    title: "Protected Class"
    description: "A deep dive into the quirks, challenges, and privileges of being who you are. Delivered Wednesdays and Saturdays."
    keywords:
        - identity
        - culture
        - individuality
        - race
        - disability
        - gender
        - sexuality
        - nc state
        - ncsu
        - raleigh
        - technician
        - student news
        - student newspaper
    album_art: /assets/img/protected-class-album-art.png

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            authors: ["Carter Pape"]
            layout: post