title: Praeci
pronounciation: "pray &middot; see"
maxim: covering NC State and Raleigh
logo: "Web Logo.png"
prod_url: http://praeci.com

timezone: America/New_York
lang: en-us

author:
    name: Carter Pape
    email: editor@praeci.com

permalink: /:categories/:title.html

plugins:
    - jekyll-feed

feed:
    path: podcast.xml

strict_front_matter: TRUE

twitter_link: https://twitter.com/PraeciNews
twitter_handle: "PraeciNews"
facebook_link: https://www.facebook.com/Praeci/
donation_link: https://www.paypal.me/CarterPape

collections:
    podcast:
        output: true
        title: "The Praeci Podcast"
        description: "NC State and Raleigh news, interviews, and more. Delivered every other Monday."
        keywords:
            - nc state
            - ncsu
            - raleigh
            - technician
            - student news
            - student newspaper
        album_art: /assets/img/podcast-album-art.png

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            authors: ["Carter Pape"]
            layout: post